In [5]:
# Se importan las librerías que se utilizarán en este archivo.
import pandas as pd
import json
import ast

In [6]:
data3 = []
with open('australian_users_items.json', "r", encoding="utf-8") as f3:
    for line in f3.readlines():
        data3.append(ast.literal_eval(line))
df_items = pd.DataFrame(data3)
df_items.head(5)

,user_id,items_count,steam_id,user_url,items
0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
1,js41637,888,76561198035864385,http://steamcommunity.com/id/js41637,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
2,evcentric,137,76561198007712555,http://steamcommunity.com/id/evcentric,"[{'item_id': '1200', 'item_name': 'Red Orchest..."
3,Riot-Punch,328,76561197963445855,http://steamcommunity.com/id/Riot-Punch,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
4,doctr,541,76561198002099482,http://steamcommunity.com/id/doctr,"[{'item_id': '300', 'item_name': 'Day of Defea..."

In [7]:
# Se eliminan las columnas irrelevantes
df_items = df_items.drop(['steam_id', 'user_url'], axis=1)

In [8]:
df_items.head(10)

,user_id,items_count,items
0,76561197970982479,277,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
1,js41637,888,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
2,evcentric,137,"[{'item_id': '1200', 'item_name': 'Red Orchest..."
3,Riot-Punch,328,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
4,doctr,541,"[{'item_id': '300', 'item_name': 'Day of Defea..."
5,MinxIsBetterThanPotatoes,371,"[{'item_id': '50', 'item_name': 'Half-Life: Op..."
6,NitemarePK,304,"[{'item_id': '240', 'item_name': 'Counter-Stri..."
7,themanwich,258,"[{'item_id': '220', 'item_name': 'Half-Life 2'..."
8,maplemage,629,"[{'item_id': '240', 'item_name': 'Counter-Stri..."
9,Wackky,0,[]

In [20]:
# Se desanida la columna items para ver su información.
df_items['playtime_forever'] = df_items['items'].apply(lambda x: x[0].get('playtime_forever') if len(x) > 0 else 0)
df_items['playtime_2weeks'] = df_items['items'].apply(lambda x: x[0].get('playtime_2weeks') if len(x) > 0 else 0)
df_items['id'] = df_items['items'].apply(lambda x: x[0].get('item_id') if len(x) > 0 else 0)
df_items['playtime_forever'] = df_items['playtime_forever'].astype(int)
df_items['playtime_2weeks'] = df_items['playtime_2weeks'].astype(int)

In [22]:
df_items.head(10)

,user_id,items_count,items,playtime_forever,playtime_2weeks,id
0,76561197970982479,277,"[{'item_id': '10', 'item_name': 'Counter-Strik...",6,0,10
1,js41637,888,"[{'item_id': '10', 'item_name': 'Counter-Strik...",0,0,10
2,evcentric,137,"[{'item_id': '1200', 'item_name': 'Red Orchest...",923,0,1200
3,Riot-Punch,328,"[{'item_id': '10', 'item_name': 'Counter-Strik...",0,0,10
4,doctr,541,"[{'item_id': '300', 'item_name': 'Day of Defea...",1131,0,300
5,MinxIsBetterThanPotatoes,371,"[{'item_id': '50', 'item_name': 'Half-Life: Op...",256,0,50
6,NitemarePK,304,"[{'item_id': '240', 'item_name': 'Counter-Stri...",3529,0,240
7,themanwich,258,"[{'item_id': '220', 'item_name': 'Half-Life 2'...",219,0,220
8,maplemage,629,"[{'item_id': '240', 'item_name': 'Counter-Stri...",5751,0,240
9,Wackky,0,[],0,0,0

In [23]:
# Se exporta el dataset limpio
df_items.to_csv('df_items.csv', index=False)